sudo apt install -y \
    anki \
    aria2 \
    build-essential \
    chessx \
    cmake \
    conky \
    dosbox \
    evilwm \
    ffmpeg \
    fish \
    gimp \
    git \
    git-svn \
    imagemagick-6.q16 \
    ipmitool \
    irssi \
    iverilog \
    k3b \
    k4dirstat \
    kitty \
    libsdl2-dev \
    mesa-utils \
    mosh \
    net-tools \
    ninja-build \
    nodejs \
    npm \
    openssh-server \
    perl-doc \
    python3-pip \
    python3-virtualenv \
    qbittorrent \
    stockfish \
    subversion \
    tmux \
    tox \
    vim \
    vlc \
    weather-util \
    whois \
    zfsutils-linux \

pip install --user \
    youtube-dl \
    yt-dlp \
